// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-seasons.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
}

// src/lib/mcp/tools/list-seasons.ts
var list_seasons_default = defineTool({
  name: "list_seasons",
  title: "List seasons",
  description: "List the tennis seasons the signed-in user created or participates in.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("seasons").select("id, name, format, status, lifecycle_status, start_date, end_date, creator_id").order("start_date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const seasons = (data ?? []).map((s) => ({ ...s, is_creator: s.creator_id === ctx.getUserId() }));
    return {
      content: [{ type: "text", text: JSON.stringify(seasons, null, 2) }],
      structuredContent: { seasons }
    };
  }
});

// src/lib/mcp/tools/get-season.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var get_season_default = defineTool2({
  name: "get_season",
  title: "Get season details",
  description: "Get a season's participants, doubles teams, and current scheduling captain.",
  inputSchema: { season_id: z.string().describe("The season id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const [season, participants, teams, captains] = await Promise.all([
      supabase.from("seasons").select("*").eq("id", season_id).maybeSingle(),
      supabase.from("season_participants").select("id, display_name, status, user_id, invited_email").eq("season_id", season_id),
      supabase.from("doubles_teams").select("id, name, player_a_id, player_b_id").eq("season_id", season_id),
      supabase.from("captain_rotation").select("participant_id, position, is_current, window_start, window_end").eq("season_id", season_id).eq("is_current", true)
    ]);
    const error = season.error ?? participants.error ?? teams.error ?? captains.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!season.data) return { content: [{ type: "text", text: "Season not found or not visible to you." }], isError: true };
    const payload = {
      season: season.data,
      participants: participants.data ?? [],
      doubles_teams: teams.data ?? [],
      current_captain: captains.data?.[0] ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-matches.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_matches_default = defineTool3({
  name: "list_matches",
  title: "List matches",
  description: "List matches in a season, optionally filtered by status (pending, scheduled, completed).",
  inputSchema: {
    season_id: z2.string().describe("The season id."),
    status: z2.string().optional().describe("Optional match status filter, e.g. scheduled or completed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("matches").select("id, round, status, side_kind, side_a_id, side_b_id, scheduled_at, location, deadline_at, completed_at").eq("season_id", season_id).order("round", { ascending: true });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-standings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_standings_default = defineTool4({
  name: "get_standings",
  title: "Get standings",
  description: "Get the current standings (wins, losses, sets, games) for a season.",
  inputSchema: { season_id: z3.string().describe("The season id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ season_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("season_standings").select("side_id, side_kind, wins, losses, sets_won, sets_lost, games_won, games_lost").eq("season_id", season_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = [...data ?? []].sort((a, b) => (b.wins ?? 0) - (a.wins ?? 0));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { standings: rows }
    };
  }
});

// src/lib/mcp/tools/schedule-match.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var schedule_match_default = defineTool5({
  name: "schedule_match",
  title: "Schedule a match",
  description: "Set the date/time and location for an existing match in a season.",
  inputSchema: {
    match_id: z4.string().describe("The match id."),
    scheduled_at: z4.string().describe("ISO 8601 date-time for the match."),
    location: z4.string().optional().describe("Optional court or venue name.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ match_id, scheduled_at, location }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const when = new Date(scheduled_at);
    if (Number.isNaN(when.getTime())) {
      return { content: [{ type: "text", text: "scheduled_at must be a valid ISO 8601 date-time." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("matches").update({
      scheduled_at: when.toISOString(),
      location: location ?? null,
      status: "scheduled",
      scheduled_by: ctx.getUserId()
    }).eq("id", match_id).select("id, status, scheduled_at, location").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Match not found or you do not have permission to update it." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { match: data }
    };
  }
});

// src/lib/mcp/tools/record-score.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var record_score_default = defineTool6({
  name: "record_match_score",
  title: "Record match score",
  description: "Record the set-by-set box score for a match and mark it completed.",
  inputSchema: {
    match_id: z5.string().describe("The match id."),
    sets: z5.array(z5.object({ side_a_games: z5.number().int(), side_b_games: z5.number().int() })).describe("Sets in order, each with games won by side A and side B. Provide 1 to 5 sets.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ match_id, sets }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (!sets.length || sets.length > 5) {
      return { content: [{ type: "text", text: "Provide between 1 and 5 sets." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let aSets = 0;
    let bSets = 0;
    for (const s of sets) {
      if (s.side_a_games > s.side_b_games) aSets++;
      else if (s.side_b_games > s.side_a_games) bSets++;
    }
    if (aSets === bSets) {
      return { content: [{ type: "text", text: "The score is tied \u2014 a winner could not be determined." }], isError: true };
    }
    const winner_side = aSets > bSets ? "a" : "b";
    await supabase.from("match_scores").delete().eq("match_id", match_id);
    const { error: scoreError } = await supabase.from("match_scores").insert(
      sets.map((s, i) => ({
        match_id,
        set_number: i + 1,
        side_a_games: s.side_a_games,
        side_b_games: s.side_b_games
      }))
    );
    if (scoreError) return { content: [{ type: "text", text: scoreError.message }], isError: true };
    const { error: resultError } = await supabase.from("match_results").upsert({ match_id, winner_side, entered_by: ctx.getUserId() }, { onConflict: "match_id" });
    if (resultError) return { content: [{ type: "text", text: resultError.message }], isError: true };
    const { error: matchError } = await supabase.from("matches").update({ status: "completed", completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", match_id);
    if (matchError) return { content: [{ type: "text", text: matchError.message }], isError: true };
    const payload = { match_id, winner_side, sets };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rxgewhprxpkxkesrnxyd";
var mcp_default = defineMcp({
  name: "aether",
  title: "Aether Tennis",
  version: "0.1.0",
  instructions: "Tools for Aether Tennis, a social tennis season platform. Use list_seasons to find the user's seasons, get_season for participants and the current scheduling captain, list_matches for the schedule, get_standings for the table, schedule_match to set a match date/time and location, and record_match_score to submit a box score.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_seasons_default, get_season_default, list_matches_default, get_standings_default, schedule_match_default, record_score_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
